[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1NZSlUe4si4U1Qvriv2oF90eF096B0RhgRJymXxtE4VI/edit?gid=0#gid=0"

[gcp_service_account]
type = "service_account"
project_id = "gifted-chimera-488201-f8"
private_key_id = "084b49ad225ec16e6faf2d81a4cd12a8774faf6f"
private_key = private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoDKZDpJpttw/u\nqJuTKfKv6lca1CS2mdH5VTJRRdtd3GdP27+Orh6L2DbZMcfaCGgTtZ+qwguU8Rok\n... (其餘省略) ...\n-----END PRIVATE KEY-----\n"
client_email = "innhelperdb@gifted-chimera-488201-f8.iam.gserviceaccount.com"
client_id = "112411358671994463440"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/innhelperdb%40gifted-chimera-488201-f8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"